### ISSUE TITLE
Problem with build_site()

### ISSUE THREAD

**Issue by Mullefa** [hadley/staticdocs#82] opened 2015-05-27 14:23 UTC
Not sure if this is a documentation or code issue.

I have just installed `staticdocs`. First port of call is `?staticdocs` which leads me to `build_site()`.

However this returns the error:

```R
Error in if (file.exists(default)) return(default) : 
  argument is of length zero
```

Here's what's happening:

- `pkg_sd_path()` is returning `NULL` as the `staticdocs/` subdirectory hasn't been created
- therefore, in the call to `load_index()` we have `file.path.ci(NULL, "index.R")`
- which is a problem as this evaluates to `character(0)`

Creating the `staticdocs/` directory (where `pkg_sd_path()` expects it to be) solves this problem.

**Comment by krlmlr** [comment] 2015-06-23 19:55
Is this a duplicate of #67?

**Closed** 2015-06-24 13:48 UTC
