### ISSUE TITLE
Option to run (and remove) \dontrun examples

### ISSUE THREAD

**Issue by trinker** [hadley/staticdocs#58] opened 2014-03-13 16:19 UTC
I tried the updated version of static docs, works well.

In the new version `build_site` lost the argument of rather or not to run the examples.  That was nice.  It may be nice to reinclude this.

Also it would be nice to have the ability to run examples that have been blotted from the CRAN check via `\dontrun{}`  If one could choose to run this documentation for a static website even though it's "editted" out of the CRAN check, that would be nice.

**Comment by hadley** [comment] 2016-08-25 14:51
Duplicate of #29

**Closed by hadley** 2016-08-25 14:51 UTC
