### ISSUE TITLE
Error in build_site with deqn

### ISSUE THREAD

**Issue by nite** [hadley/staticdocs#101] opened 2016-06-06 21:58 UTC
The following error occurs when the ocs contain a line like this: 
`#' \deqn{\tilde{f}(x) = \frac{1}{n} ∑_{i=1}^n f(x, x_{iC}),}
`
Any ideas? 

Error in x[[length(x) - 1]] : 
  attempt to select less than one element in get1index <real>
In addition: There were 15 warnings (use warnings() to see them)
> traceback()
29: lapply(x, to_html, ...)
28: to_html.list(x, ...)
27: unlist(to_html.list(x, ...))
26: stri_c(..., sep = sep, collapse = collapse, ignore_null = TRUE)
25: str_c(unlist(to_html.list(x, ...)), collapse = "")
24: to_html.TEXT(x[[length(x) - 1]], ...)
23: stri_c(..., sep = sep, collapse = collapse, ignore_null = TRUE)
22: str_c("$$", to_html.TEXT(x[[length(x) - 1]], ...), "$$")
21: to_html.deqn(X[[i]], ...)
20: FUN(X[[i]], ...)
19: lapply(x, to_html, ...)
18: to_html.list(x, ...)
17: unlist(to_html.list(x, ...))
16: stri_c(..., sep = sep, collapse = collapse, ignore_null = TRUE)
15: str_c(unlist(to_html.list(x, ...)), collapse = "")
14: to_html.TEXT(x, ...)
13: parse_section(x, "Details", ...)
12: to_html.details(X[[i]], ...)
11: FUN(X[[i]], ...)
10: lapply(x, to_html, ...)
9: to_html.list(sections, topic = out$name, ...)
8: to_html(sections, topic = out$name, ...)
7: lapply(x, f)
6: unlist(lapply(x, f))
5: Filter(function(x) !is.null(x) & length(x), x)
4: compact(to_html(sections, topic = out$name, ...))
3: to_html.Rd_doc(rd, env = new.env(parent = globalenv()), topic = str_replace(basename(paths[[i]]), 
       "\\.html$", ""), pkg = pkg)
2: build_topics(pkg)
1: staticdocs::build_site(".", examples = F)

**Comment by jranke** [comment] 2016-06-08 19:10
Maybe it is caused by the special sum character?

**Comment by cderv** [comment] 2016-07-18 18:22
I have the same problem with `to_html.deqn` which returns an error. 

```r
Error in x[[length(x) - 1]] : 
  attempt to select less than one element in get1index <real>
```
My problem is with this equation `\deqn{e_{i} = X_{i+1} - X_{i} + gradU(X_{i})}`. Tag *\deqn* is parsed with `to_html.deqn` with `pkg$mathjax` is `TRUE` 
```r
function (x, pkg, ...) 
{
    stopifnot(length(x) <= 2)
    if (pkg$mathjax) {
        str_c("$$", to_html.TEXT(x[[length(x) - 1]], ...), "$$")
    }
    else {
        str_c("<pre class = 'eq'>", to_html.TEXT(x[[length(x)]], 
            ...), "</pre>")
    }
}
```
If anyone one to test, this is the object use as `x` in `to_html.deqn` (obtain with `dput`)
```r
structure(list(structure(list(structure("e_{i} = X_{i+1} - X_{i} + gradU(X_{i})", Rd_tag = "VERB", class = c("VERB", 
"Rd_content", "character"))), class = c("Rd_content", "list"))), Rd_tag = "\\deqn", class = c("deqn", 
"Rd_content", "list"))
```
`x` is of length 1. so `x[[length(x) - 1]]` throws an error. 
Anybody can explain why we have to do `length(x) - 1` and not `length(x)` here ?? 

Is this a bug ?

**Comment by cderv** [comment] 2016-07-19 05:52
@randy3k, as you made the PR for mathjax support, you may have the answer. Thanks!

**Comment by randy3k** [comment] 2016-07-19 06:05
Ah...my PR contained a bug.

The syntax of  `\deqn` is `\deqn{latex}{ascii}` and I have assumed that there are always arguments. However it can also be used as `\deqn{latexascii}` (only one argument).

There are two options.

1) open a PR and change `x[[length(x) - 1]]` to `x[[1]]`
2) do `\deqn{latex}{ascii}` instead of `\deqn{latexascii}`

**Comment by cderv** [comment] 2016-07-19 08:00
I see you've made the PR. Hope it will be merged soon! Lots of PR in stand-by

Thanks.

**Closed** 2016-09-21 21:02 UTC
