### ISSUE TITLE
error on build

### ISSUE THREAD

**Issue by davidcarslaw** [hadley/staticdocs#57] opened 2014-03-12 14:04 UTC
I have tried to run build_site on my package and get the error below (this on Mac or Windows from the working directory of my package). Any suggestions as to the cause?

     build_site(pkg = ".", launch = interactive())
    Error in if (file.exists(default)) return(default) : 
      argument is of length zero

Thanks
David

**Comment by andrie** [comment] 2015-01-19 07:47
Duplicate of #67 where the problem is described in the issue itself.

**Closed** 2015-06-24 13:48 UTC
